---
title: "Data Wrangling"
output: html_notebook
---


```{r}
Series_sample_id <- c("GSM1580869", "GSM1580870", "GSM1580871", "GSM1580872", "GSM1580873", "GSM1580874", "GSM1580875", "GSM1580876", "GSM1580877", "GSM1580878", "GSM1580879", "GSM1580880", "GSM1580881", "GSM1580882", "GSM1580883", "GSM1580884", "GSM1580885", "GSM1580886", "GSM1580887", "GSM1580888", "GSM1580889", "GSM1580890", "GSM1580891", "GSM1580892", "GSM1580893", "GSM1580894", "GSM1580895", "GSM1580896", "GSM1580897", "GSM1580898", "GSM1580899", "GSM1580900", "GSM1580901", "GSM1580902", "GSM1580903", "GSM1580904", "GSM1580905", "GSM1580906", "GSM1580907", "GSM1580908", "GSM1580909", "GSM1580910", "GSM1580911", "GSM1580912", "GSM1580913", "GSM1580914", "GSM1580915", "GSM1580916")

Sample_title<- c("C_0002", "C_0003", "C_0004", "C_0005", "C_0006", "C_0008", "C_0009", "C_0010", "C_0011", "C_0012", "C_0013", "C_0014", "C_0015", "C_0016", "C_0017", "C_0018", "C_0019", "C_0020", "C_0021", "C_0022", "C_0023", "C_0024", "C_0025", "C_0026", "C_0029", "C_0031", "C_0032", "C_0033", "C_0035", "C_0036", "C_0037", "C_0038", "C_0039", "C_0050", "C_0053", "C_0060", "C_0061", "C_0062", "C_0065", "C_0069", "C_0070", "C_0071", "C_0075", "C_0076", "C_0077", "C_0081", "C_0082", "C_0083", "C_0087", "H_0001", "H_0002", "H_0003", "H_0005", "H_0006", "H_0007", "H_0008", "H_0009", "H_0010", "H_0012", "H_0013", "H_0539", "H_0657", "H_0658", "H_0681", "H_0695", "H_0700", "H_0726", "H_0740", "H_0750")

diagnosis <- c("diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Neurologically normal", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease", "diagnosis: Huntington's Disease")

age_of_death <- c("age of death: 73", "age of death: 91", "age of death: 82", "age of death: 97", "age of death: 86", "age of death: 91", "age of death: 81", "age of death: 79", "age of death: 63", "age of death: 66", "age of death: 69", "age of death: 79", "age of death: 61", "age of death: 58", "age of death: 70", "age of death: 66", "age of death: 73", "age of death: 60", "age of death: 76", "age of death: 61", "age of death: 62", "age of death: 69", "age of death: 61", "age of death: 88", "age of death: 93", "age of death: 53", "age of death: 57", "age of death: 43", "age of death: 46", "age of death: 40", "age of death: 44", "age of death: 57", "age of death: 80", "age of death: 74", "age of death: 69", "age of death: 76", "age of death: 78", "age of death: 87", "age of death: 86", "age of death: 54", "age of death: 68", "age of death: 106", "age of death: 52", "age of death: 46", "age of death: 36", "age of death: 55", "age of death: 57", "age of death: 66", "age of death: 64", "age of death: 55", "age of death: 69", "age of death: 71", "age of death: 48", "age of death: 40", "age of death: 72", "age of death: 43", "age of death: 68", "age of death: 59", "age of death: 68", "age of death: 57", "age of death: 54", "age of death: 61", "age of death: 48", "age of death: 69", "age of death: 55", "age of death: 50", "age of death: 50", "age of death: 75", "age of death: 53")

metadata_df<- data.frame(Series_sample_id,Sample_title,diagnosis,age_of_death)

```
```{r}
#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#
#BiocManager::install("bigPint")
library(bigPint)

data(se_soybean_cn_sub)

```
